import { Composition } from "remotion";
import { REEL } from "./brand";
import { calculateReelMetadata } from "./calculate-metadata/calculate-metadata";
import sampleProps from "./generated/latest.json";
import { Reel } from "./Reel";
import { ReelProps, reelPropsSchema } from "./schema";

// Generated by `npm run props` (scripts/build-reel-props.mjs). Committed so the
// Studio opens with something to look at straight after a fresh clone.
const defaultProps = reelPropsSchema.parse(sampleProps) as unknown as ReelProps;

export const RemotionRoot: React.FC = () => {
  return (
    <Composition
      id="Reel"
      component={Reel}
      fps={REEL.fps}
      width={REEL.width}
      height={REEL.height}
      defaultProps={defaultProps}
      schema={reelPropsSchema}
      calculateMetadata={calculateReelMetadata}
    />
  );
};
